import Head from 'next/head'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Instagram</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" type="image/icon"
          href="https://cdn2.iconfinder.com/data/icons/social-media-2285/512/1_Instagram_colored_svg_1-512.png" />
      </Head>

    </div>
  )
}
